name: future-motion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohttp=3.7.0
  - antlr-python-runtime=4.8
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=3.0.1
  - attrs=22.1.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cachetools=5.2.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - chardet=3.0.4
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=38.0.1
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.7.99
  - cuda-gdb=11.8.86
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.8.87
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3.2
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.2
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.29
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - hydra-core=1.1.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=5.1.0
  - importlib_resources=5.10.1
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.7
  - jupyter_console=6.4.3
  - jupyter_core=4.11.2
  - jupyter_server=1.18.1
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.3
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nsight-compute=2022.3.0.22
  - nspr=4.33
  - nss=3.74
  - oauthlib=3.2.2
  - omegaconf=2.1.1
  - openh264=2.1.1
  - openssl=1.1.1s
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - prometheus_client=0.14.1
  - promise=2.3
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-lightning=1.5.10
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - send2trash=1.8.0
  - sentry-sdk=1.11.1
  - setproctitle=1.1.10
  - shortuuid=1.0.11
  - sip=6.6.2
  - smmap=3.0.5
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.13.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=0.13.0
  - torchmetrics=0.11.0
  - torchvision=0.14.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - transforms3d=0.4.1
  - tzdata=2022g
  - urllib3=1.26.12
  - wandb=0.13.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.2
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - x264=1!161.3030
  - xz=5.2.8
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - array-record==0.5.1
    - astunparse==1.6.3
    - black==20.8b0
    - clang==5.0
    - click==7.1.2
    - cloudpickle==2.2.0
    - contourpy==1.2.1
    - dacite==1.8.1
    - dask==2023.3.1
    - dataclass-array==1.5.1
    - dm-tree==0.1.8
    - einops==0.7.0
    - einsum==0.3.0
    - etils==1.5.2
    - filelock==3.13.1
    - flatbuffers==24.3.25
    - fsspec==2024.3.1
    - gast==0.4.0
    - google-auth==2.16.2
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.63.0
    - grpcio==1.59.2
    - gym==0.21.0
    - h5py==3.1.0
    - huggingface-hub==0.21.4
    - imageio==2.32.0
    - immutabledict==2.2.0
    - jax==0.4.26
    - keras==2.12.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kmeans-pytorch==0.3
    - lark==1.1.9
    - lazy-loader==0.4
    - libclang==16.0.6
    - local-attention==1.9.0
    - locket==1.0.0
    - markdown-it-py==3.0.0
    - matplotlib==3.6.1
    - mdurl==0.1.2
    - ml-dtypes==0.4.0
    - mypy-extensions==0.4.3
    - networkx==3.2.1
    - numpy==1.23.0
    - opencv-python==4.6.0.66
    - openexr==1.3.9
    - opt-einsum==3.3.0
    - pandas==1.5.3
    - partd==1.4.1
    - pathspec==0.10.2
    - plotly==5.13.1
    - protobuf==3.20.3
    - pyarrow==10.0.0
    - pygments==2.16.1
    - pywavelets==1.4.1
    - regex==2022.10.31
    - rich==13.6.0
    - safetensors==0.4.2
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - setuptools==67.6.0
    - shellingham==1.5.4
    - six==1.15.0
    - tenacity==8.2.2
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.2
    - tensorflow==2.12.0
    - tensorflow-addons==0.23.0
    - tensorflow-datasets==4.9.3
    - tensorflow-estimator==2.12.0
    - tensorflow-graphics==2021.12.3
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorflow-metadata==1.14.0
    - tensorflow-probability==0.19.0
    - termcolor==1.1.0
    - tifffile==2023.9.26
    - tokenizers==0.15.2
    - toolz==0.12.1
    - torch-kmeans==0.2.0
    - transformers==4.39.0
    - trimesh==4.3.1
    - typed-ast==1.5.4
    - typeguard==2.13.3
    - typer==0.9.0
    - typing-extensions==3.7.4.3
    - visu3d==1.5.1
    - vit-pytorch==1.6.5
    - waymo-open-dataset-tf-2-12-0==1.6.4
    - wrapt==1.12.1
    - torch-dct==0.1.6
    - nc-toolbox @ git+https://github.com/felixsh/nc-toolbox
    - gdown==5.2.0