# @package _global_

defaults:
  - _self_
  - trainer: womd
  - model: scr_womd
  - datamodule: h5_womd
  - callbacks: wandb
  - loggers: wandb
  - resume: empty

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

work_dir: ${hydra:runtime.cwd}
seed: 2023
action: fit # fit, validate, test

# Shared parameter for motion planning
use_ego_nav: False
nav_with_route: False
nav_with_goal: False
nav_route_late_fusion: False
nav_goal_late_fusion: False
use_nav_loss: False
