_target_: hptr_modules.data_modules.data_h5_nuplan.DataH5nuplan

data_dir: ""
filename_train: training_mini
filename_val: validation_mini
filename_test: testing_mini
n_agent: 64

batch_size: 3
num_workers: 4